---
title: "141xp"
author: "Karishma Raghuram"
date: "2023-05-24"
output:
  html_document: default
  pdf_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## R Markdown

```{r}
sleepdata <- read.csv("Dataset.csv")
head(sleepdata)
```



```{r}
#install.packages("stringr")
#library("stringr")

summary(sleepdata)
#install.packages("vtable")


sleepdata1<- sleepdata[!duplicated(sleepdata$RecordNo),]

head(sleepdata1)

#table of variable basics 
library(vtable)
#data(sleepdata1)
vt(sleepdata1, out = 'kable' )
sumtable(sleepdata1, out = 'kable')

#gender stratification FEMALE
gender.female <- sleepdata1[sleepdata1$Gender.Male.Female. == "female",]
#(head(gender.female))

shapiro.test(gender.female$Arousals.with.PLM)
shapiro.test(gender.female$ESS)

female_K = cor(gender.female$Arousals.with.PLM, gender.female$ESS, method = "kendall")
female_K

female_S = cor(gender.female$Arousals.with.PLM, gender.female$ESS, method = "spearman")
female_S

female_P = cor(gender.female$Arousals.with.PLM, gender.female$ESS, method = "pearson")
female_P

#gender stratification MALE
gender.male<- sleepdata1[sleepdata1$Gender.Male.Female. == "male",]
#(head(gender.male))

shapiro.test(gender.male$Arousals.with.PLM)
shapiro.test(gender.male$ESS)

male_K = cor(gender.male$Arousals.with.PLM, gender.male$ESS, method = "kendall")
male_K

male_S = cor(gender.male$Arousals.with.PLM, gender.male$ESS, method = "spearman")
male_S

male_P = cor(gender.male$Arousals.with.PLM, gender.male$ESS, method = "pearson")
male_P
```






